config/routes.rb
Portfolio::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/games"
  get "static_pages/software"
  get "static_pages/web"
  get "static_pages/contact"

  root 'static_pages#home'

  match '/web',    to: 'static_pages#web',    via: 'get'
  match '/games',    to: 'static_pages#games',    via: 'get'
  match '/software',    to: 'static_pages#software',    via: 'get'
  match '/contact',    to: 'static_pages#contact',    via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def games
  end

  def software
  end

  def web
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Alex Stout"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">Alex Stout</a>
    &copy; 2014
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Alex", root_path, id: "logo-first" %>
      <%= link_to "Stout", root_path, id: "logo-last" %>
      <div id="navigation-group">
        <div id="nav-btn-group" class="btn-group">
          <%= link_to "Home",    root_path, class: "btn btn-default" %>
          <%= link_to "Software",    software_path, class: "btn btn-default" %>
          <%= link_to "3D && Games",    games_path, class: "btn btn-default" %>
          <%= link_to "Web",    web_path, class: "btn btn-default" %>
          <%= link_to "Contact",    contact_path, class: "btn btn-default" %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
        <div class="inner-padding15">
            <% flash.each do |key, value| %>
                <div class="alert alert-<%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
            <%= render 'layouts/footer' %>
            <%= debug(params) if Rails.env.development? %>
        </div>
    </div>
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/games.html.erb
<h1>StaticPages#games</h1>
<p>Find me in app/views/static_pages/games.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Alex Stout's Portfolio</h1>

  <h2>
    This is the home page for
    <a href="#">Alex Stout's</a>
    Portfolio.
  </h2>

</div>

<%= link_to image_tag("avatar.png", alt: "Alex Stout", id: "img_avatar"), 'http://alexstout.weebly.com/' %>

app/views/static_pages/software.html.erb
<h1>StaticPages#software</h1>
<p>Find me in app/views/static_pages/software.html.erb</p>

app/views/static_pages/web.html.erb
<h1>StaticPages#web</h1>
<p>Find me in app/views/static_pages/web.html.erb</p>